[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/heal"
  to = "/heal.html"
  status = 200

[[redirects]]
  from = "/portal"
  to = "/portal.html"
  status = 200

[[redirects]]
  from = "/musik"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
